uploads = []
generated = []

[[outputs]]
id = "HTufxEHDUdnLLZ_AdM07U"
uri = "file://.local/downloads/solar-report-project-1.pdf"
type = "pdf"
title = "Your Solar Report — In House Consulting (1928 Skull Springs Rd, West Point CA)"
